import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[cursor]
style = {shape="Block", blinking="Always"}

# [mouse.url.launcher]
# program = "open"
# modifiers = "Command"

[window.padding]
x = 5
y = 0

[font]
size = 13

[font.normal]
family = "Monaco"
style = "Regular"

[font.bold]
family = "Monaco"
style = "Bold"

[font.italic]
family = "Monaco"
style = "Italic"

[font.bold_italic]
family = "Monaco"
style = "Bold Italic"
