import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[cursor]
style = {shape="Block", blinking="Always"}

# [mouse.url.launcher]
# program = "open"
# modifiers = "Command"

[window.padding]
x = 3
y = 0

[font]
size = 13

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[window]
option_as_alt = "OnlyLeft"
opacity = 1

